### ISSUE TITLE
method get_compuScaleContents() of class CompuScale returns None

### ISSUE THREAD

**Issue by loulin11** [girishchandranc/autosarfactory#30] opened 2024-12-04 03:45 UTC
Hello girishchandranc,

When I try to get the scale info ( node "COMPU-RATIONAL-COEFFS") of compute method in the loaded arxml files,  the method get_compuScaleContents() return None but there is indeed a "COMPU-RATIONAL-COEFFS" node under the node "COMPU-SCALE".

And when I use the get_children() method to find the sub-nodes of "COMPU-SCALE", nothing returns.

I checked the demo arxml "dataTypes.arxml" in the folder \Examples\generated，there is the same problem when I try to read the node "COMPU-RATIONAL-COEFFS" : 

            <COMPU-METHOD>
              <SHORT-NAME>cm2</SHORT-NAME>
              <COMPU-INTERNAL-TO-PHYS>
                <COMPU-SCALES>
                  <COMPU-SCALE>
                    <COMPU-RATIONAL-COEFFS>
                      <COMPU-NUMERATOR>
                        <V>100</V>
                        <V>200</V>
                        <V>300</V>
                      </COMPU-NUMERATOR>
                    </COMPU-RATIONAL-COEFFS>
                  </COMPU-SCALE>
                </COMPU-SCALES>
              </COMPU-INTERNAL-TO-PHYS>
            </COMPU-METHOD>

Could you please check it out? thanks!

Lin

**Comment by girishchandranc** [comment] 2024-12-08 20:06
hi @loulin11 ,
Thanks for reporting this. The issue is fixed and is already in the main. A test has been added to prove working https://github.com/girishchandranc/autosarfactory/blob/14567dd0343278de2170c18bd2bab8b4e1afd130/tests/test_autosarmodel.py#L702.

Please check and let me know if it works for you.

**Comment by girishchandranc** [comment] 2024-12-10 13:06
hi @loulin11 , as mentioned in my previous comment, the issue is fixed. Closing the ticket. 
Please feel free to reopen if this doesn't work for you.
Thanks!

**Closed by girishchandranc** 2024-12-10 13:06 UTC

**Comment by loulin11** [comment] 2024-12-11 03:18
Hi girishchandranc,

yes, I tried in my autosar project and the issue is solved, thanks a lot!
